apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  selector:
    app: my-clojure-app
  ports:
    - protocol: TCP
      port: 30000       # Port to access inside the cluster, we wont
                        # really use this at all
      targetPort: 3000  # Port of the container
      nodePort: 30007   # The port to expose on the Minikube node (between 30000-32767)
  type: NodePort
