# Source: onechart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blah-app
  namespace: default
  labels:
    helm.sh/chart: onechart-0.73.0
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: blah-app
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubectl.kubernetes.io/default-container: blah-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: onechart
      app.kubernetes.io/instance: blah-app
  template:
    metadata:
      annotations:
        checksum/config: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      labels:
        app.kubernetes.io/name: onechart
        app.kubernetes.io/instance: blah-app
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: blah-app
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        securityContext: {}
      initContainers: null
      securityContext:
        fsGroup: 999

---
# Source: onechart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: blah-app
  namespace: default
  labels:
    helm.sh/chart: onechart-0.73.0
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: blah-app
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: blah-app




---
# My load balancer
apiVersion: v1
kind: Service
metadata:
  name: blah-lb
  annotations:
    load-balancer.hetzner.cloud/location: nbg1 
spec:
  selector:
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: blah-app
  # selector:
  #   app: blah-app
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  # ports:
  #   - port: 8765
  #     targetPort: 9376
  type: LoadBalancer
---












