# Source: onechart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blah-app-not-used
  namespace: default
  labels:
    app: bbb
  annotations:
    kubectl.kubernetes.io/default-container: blah-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbb
  template:
    metadata:
      annotations:
        checksum/config: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      labels:
        app: bbb
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: blah-app
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        securityContext: {}
      initContainers: null
      securityContext:
        fsGroup: 999

---
apiVersion: v1
kind: Service
metadata:
  name: blah-app-service
  namespace: default
  labels:
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: bbb

---
apiVersion: v1
kind: Service
metadata:
  name: blah-lb
  annotations:
    load-balancer.hetzner.cloud/location: nbg1 
spec:
  selector:
    app: bbb
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: LoadBalancer
