# Source: onechart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blah-app-not-used
  namespace: default
  labels:
    app: bbb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbb
  template:
    metadata:
      labels:
        app: bbb
    spec:
      containers:
#      - image: nginx:latest
      - image: fenton/my-clojure-app
        imagePullPolicy: IfNotPresent
        name: blah-app
        ports:
        - containerPort: 3000
          name: node-port-name
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        securityContext: {}
      initContainers: null
      securityContext:
        fsGroup: 999

---
apiVersion: v1
kind: Service
metadata:
  name: blah-app-service
  namespace: default
  labels:
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: node-port-name
  selector:
    app: bbb

---
apiVersion: v1
kind: Service
metadata:
  name: blah-lb
  annotations:
    load-balancer.hetzner.cloud/location: nbg1 
spec:
  selector:
    app: bbb
  ports:
    - port: 80
      targetPort: node-port-name
  type: LoadBalancer
